### ISSUE TITLE
Slim skin issue

### ISSUE THREAD

**Issue by cowsha** [samolego/FabricTailor#51] opened 2022-03-18 12:50 UTC
Slim skin changes to normal after i restart game.

**Comment by samolego** [comment] 2022-03-18 13:34
Please provide more info (as how to reproduce error) & logs. Thanks :)

**Comment by samolego** [comment] 2022-03-22 17:43
Does any other data dissappaer? Which launcher are you using?

**Comment by samolego** [comment] 2022-03-23 07:30
It's probably due to tlauncher, since it has some skin patches.
I'm not supporting it due to piracy, so I'm closing this.

**Closed by samolego** 2022-03-23 07:30 UTC
Labels: bug
