### ISSUE TITLE
[BUG] Connection timed out freeze the server

### ISSUE THREAD

**Issue by mastermc05** [samolego/FabricTailor#47] opened 2021-12-21 10:04 UTC
## For skin fetching problems
- [ ] I have tried generating skin manually on [mineskin.org](https://mineskin.org/) and it works there.

**Describe the bug**
the server freeze for 2 minutes when this mod have an error, may you make it async pls?
A clear description of what the bug is.

**To Reproduce**

1. a player tries to join the server
2. server freeze (no ticking, ignoring the console) 
3. all the players are disconnected because their client didn't receive the PING/PONG packet 
4. first message after freeze is the tailor's error message, meaning that it just finished that task, not other task (i think it was trying to get his skin) 
5. server works normally, the players can connect back 

**Logs**
[12:47:50] [Server thread/ERROR]: [FabricTailor] An error occurred: Connection timed out
[12:47:50] [Server thread/INFO]: Volchara5581[**] logged in with entity id 693 at (0.5, 126.0, 0.5)
[12:47:50] [Server thread/INFO]: Volchara5581 joined the game
[12:47:50] [Server thread/INFO]: Volchara5581 lost connection: Timed out
[12:47:50] [Server thread/INFO]: Volchara5581 left the game
[12:47:50] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 129411ms or 2588 ticks behind
[12:47:50] [Server thread/INFO]: MrMinKitt lost connection: Disconnected
[12:47:50] [Server thread/INFO]: MrMinKitt left the game
[12:47:51] [Server thread/INFO]: operator lost connection: Disconnected
[12:47:51] [Server thread/INFO]: operator left the game
[12:47:51] [Server thread/WARN]: handleDisconnection() called twice
[12:47:51] [Server thread/INFO]: com.mojang.authlib.GameProfile@665052d7[id=null,name=Volchara5581,properties={},legacy=false] (*) lost connection: Disconnected
[12:47:51] [Server thread/INFO]: com.mojang.authlib.GameProfile@32155e0d[id=null,name=Volchara5581,properties={},legacy=false] (*) lost connection: Disconnected
[12:47:51] [Server thread/INFO]: com.mojang.authlib.GameProfile@34b8e222[id=null,name=Laskairk,properties={},legacy=false] (*) lost connection: Disconnected
[12:47:51] [Server thread/INFO]: com.mojang.authlib.GameProfile@a0c6da6[id=null,name=Laskairk,properties={},legacy=false] (*) lost connection: Disconnected
[12:47:51] [Server thread/INFO]: Laskairk[*] logged in with entity id 694 at (9960.513486992751, 75.0, 1804.5230337922756)
If you have any errors, please paste them as well. If possible, please use pasting site.

*Are you using any other mods?*

**Additional context**

**Comment by mastermc05** [comment] 2021-12-21 10:46
[12:47:50] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 129411ms or 2588 ticks behind
this line tells the time

**Comment by mastermc05** [comment] 2021-12-21 12:18
and also a question, may it be your mod the reason why sometimes the players disconnects but the server still thinks that it is still connected, and mobs may kill them? i'm just still unsure what mod is the reason

**Comment by samolego** [comment] 2021-12-21 17:11
Seems like ping packet is doing sth weird as you've described ...

About "keeping player online"; that might be caused by the server lag? As FabricTailor doesn't mess with the logout ...

**Comment by samolego** [comment] 2021-12-21 17:11
Seems like ping packet is doing sth weird as you've described ...

About "keeping player online"; that might be caused by the server lag? As FabricTailor doesn't mess with the logout ...

**Comment by samolego** [comment] 2021-12-21 17:13
I somehow messed the async skin fetching that used to be present ...

**Comment by mastermc05** [comment] 2021-12-22 04:38
> Thanks for report!
> 
> About "keeping player online"; that might be caused by the server lag? As FabricTailor doesn't mess with the logout ...

thanks, then it is another mod

**Comment by samolego** [comment] 2022-01-15 22:13
Fixed in 1.8.0

**Closed by samolego** 2022-01-15 22:13 UTC
Labels: bug
